# Site settings
title: Aaron S. Wolf's homepage
email: aswolf@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Aaron S. Wolf is a Turner Postdoctoral Scholar in the Earth and Environmental
  Sciences Department at the University of Michigan. This is his homepage.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  aswolf

# Build settings
# NOTE MUST BE KRAMDOWN for markdown blocks within html
markdown: kramdown
pygments: true
permalink:  /:categories/:title.html
